admin_email: ankit.gupta@razorpay.com
admin_password: admin
admin_user: superadmin
allow_reports: false
base_path: ""
cleanup_interval: 12h0m0s
cmd_file: /bin/bash
db_conn: postgres
db_database: ${DATABASE_NAME}
db_host: ${DATABASE_URL}
db_port: 5432
db_user: ${DATABASE_USERNAME}
db_pass: ${DATABASE_PASSWORD}
description: Razorpay Status Page
disable_logs: false
domain: statping.stage.razorpay.in
go_env: ""
is_aws: false
is_docker: false
max_idle_conn: 25
max_life_conn: 180
max_open_conn: 25
name: Razorpay Status Page
postgres_sslmode: require
remove_after: 2160h0m0s
sample_data: true
sass: /usr/local/bin/sass
use_assets: true
use_cdn: false
version: ""