name: CI
on: [ push ]
jobs:
  cancel:
    runs-on: [self-hosted, ubuntu-latest]
    name: Cancel Previous Runs
    if: always()
    steps:
      - uses: styfle/cancel-workflow-action@d57d93c3a8110b00c3a2c0b64b8516013c9fd4c9
        if: github.ref != 'refs/heads/master'
        name: cancel old workflows
        id: cancel
        with:
          access_token: ${{ github.token }}
      - if: github.ref == 'refs/heads/master'
        name: Don't cancel old workflows
        id: dont_cancel
        run: |
          echo "Don't cancel old workflow"

  build-statping-docker-image:
    name: Docker image - statping
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          dockerfile: ./Dockerfile
          build_args: GIT_COMMIT_HASH=${{ github.sha }},GIT_TOKEN=${{ secrets.GIT_TOKEN }}
          push: true
          tags: service_${{ github.sha }}

  fmt:
    name: fmt
    runs-on: [self-hosted, ubuntu-latest]
    continue-on-error: false
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: format
        uses: docker://golang:1.13-alpine3.10
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          entrypoint: /bin/sh
          args: ./scripts/run_tests.sh fmt drone

  workflow_status:
    runs-on: [self-hosted, ubuntu-latest]
    name: Update Status Check
    needs: [ build-statping-docker-image]
    if: always()
    steps:
      - name: Failed
        id: failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo 'Failing the workflow for github status check.'
          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
          -d '{ "state" : "failure" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
          exit 1
      - name: Success
        if: steps.failed.conclusion == 'skipped'
        run: |
          echo 'Status check has passed!'
          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
          -d '{ "state" : "success" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
          exit 0
