on:
  pull_request:
    types: [ opened, reopened, edited, synchronize]
name: Mandatory-Jira-Check
jobs:

  Find-Jira-Id:
    name: Find-Jira-Id
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: Razorpay/check-commit-jira
          path: .github/actions/check-commit-jira
          ref:  combined_check
          token: ${{ secrets.GIT_TOKEN }}
      - name: Login
        uses: ./.github/actions/check-commit-jira/jira-login
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      #  Find Issue on JIRA
      - name: Get Issue Key
        id: find
        uses: ./.github/actions/check-commit-jira/jira-issue-check
        with:
          from: pull_request
      #  Print JIRA ID found on jira
      - name: Find issue info
        run: echo "Issue ${{ steps.find.outputs.issue }} was found"
